name: pymc
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyter
  - ipykernel
  - ipywidgets
  - numpy
  - pymc>=5
  - cxx-compiler
  - pytensor
  - nutpie
  - numba
  - arviz
  - matplotlib
  - scipy
  - scikit-learn
  - graphviz
  - jaxlib
  - jax
  - blackjax
  - numpyro
  - pip
  - pandas